apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: eks.privileged
  creationTimestamp: "2022-12-15T20:04:51Z"
  generateName: waypoint-server-
  labels:
    app.kubernetes.io/instance: waypoint
    app.kubernetes.io/name: waypoint
    component: server
    controller-revision-hash: waypoint-server-77949c779
    helm.sh/chart: waypoint-0.1.17
    statefulset.kubernetes.io/pod-name: waypoint-server-0
  name: waypoint-server-0
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: waypoint-server
    uid: 49bd1c8a-fbe1-4e28-b6e1-2c927e543d7f
  resourceVersion: "41153"
  uid: 5d814046-3075-4a50-9d7c-126541de8b5b
spec:
  containers:
  - args:
    - server
    - run
    - -accept-tos
    - -db=/data/data.db
    - -listen-grpc=0.0.0.0:9701
    - -listen-http=0.0.0.0:9702
    - -listen-http-insecure=0.0.0.0:9703
    - -vv
    command:
    - waypoint
    env:
    - name: HOME
      value: /home/waypoint
    image: docker.io/hashicorp/waypoint:latest
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 2
      initialDelaySeconds: 5
      periodSeconds: 3
      successThreshold: 1
      tcpSocket:
        port: grpc
      timeoutSeconds: 5
    name: waypoint
    ports:
    - containerPort: 9701
      name: grpc
      protocol: TCP
    - containerPort: 9702
      name: https
      protocol: TCP
    - containerPort: 9703
      name: http
      protocol: TCP
    resources:
      limits:
        cpu: "0"
        memory: "0"
      requests:
        cpu: "0"
        memory: "0"
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /data
      name: data-default
    - mountPath: /home/waypoint
      name: home
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-cbnc8
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: waypoint-server-0
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 100
  serviceAccount: waypoint
  serviceAccountName: waypoint
  subdomain: waypoint-server
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: data-default
    persistentVolumeClaim:
      claimName: data-default-waypoint-server-0
  - emptyDir: {}
    name: home
  - name: kube-api-access-cbnc8
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-12-15T20:04:51Z"
    message: no nodes available to schedule pods
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
  qosClass: BestEffort
