---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bestir-identity-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bestir-identity-service
  template:
    metadata:
      labels:
        app: bestir-identity-service
    spec:
      containers:
      - name: bestir-identity-service
        image: 222267256875.dkr.ecr.us-east-1.amazonaws.com/bestir-identity-service:latest
        env: 
        - name: DD_DISABLE
          value: "true"
        - name: API_ADDRESS
          value: "0.0.0.0:8080"
        - name: IDENTITY_DB_USER
          value: "usr" 
        - name: IDENTITY_DB_PASSWORD
          value: "identity" 
        - name: IDENTITY_DB_HOST
          value: "127.0.0.1" 
        - name: IDENTITY_DB_NAME
          value: "identity" 
        - name: IDENTITY_DB_PORT
          value: "3306" 
        - name: ENABLE_MIGRATE
          value: "true" 
        ports:
        - name: web
          containerPort: 8080
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 256Mi
            cpu: 250m
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - general
      # tolerations:
      # - key: team
      #   operator: Equal
      #   value: devops
      #   effect: NoSchedule
